name: Admin_Workflow

env:
  DEV_ORG_TYPE: PRODUCTION
  DEV_ORG_USERNAME: 'yogaraj@gscloudsolutions.com.enterprise'
  DEV_ORG_PASSWORD: ${{ secrets.DEV_ORG_PASSWORD }}

on:
  workflow_dispatch:
    inputs:
      CHANGESET_NAME:
        description: 'Changeset name'
        required: true
        default: 'test'
      COMMIT_MESSAGE:
        description: 'Commit message'
        required: true
        default: 'Created from Changeset'
      BRANCH_NAME:
        description: 'Branch Name'
        required: true
        default: 'test_branch'
      ORG_USERNAME:
        description: 'Salesforce Org Username'
      ORG_PASSWORD:
        description: 'Salesforce Org Password with Security Token'

jobs:
  checkout_git_branch:
    runs-on: ubuntu-latest
    container:
      image: gscloudsolutions/devops-mate:stable
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Retrieve Changeset
        run: |
          echo 'Checking out git branch'
          echo $GITHUB_WORKSPACE
          echo $CHANGESET_NAME
          echo $COMMIT_MESSAGE
          echo $BRANCH_NAME
          git checkout -b "feature/$BRANCH_NAME"
          echo 'Pulling changeset and commiting it to checked out branch'
          sfRetrieve src-format -u ${{ env.DEV_ORG_USERNAME }} -s ${{ env.DEV_ORG_PASSWORD }} -t ${{ env.DEV_ORG_TYPE }} -n "$CHANGESET_NAME" -p $GITHUB_WORKSPACE
          ls -a
          git add --all
          git commit -m "$COMMIT_MESSAGE"
          git push
