name: Main_Merge_Workflow

env:
  GITHUB_PR_DESTINATION_BRANCH: ${{ github.ref_name }}
  QA_PACKAGE_DIR: 'QADir'
  QA_ORG_USERNAME: 'yogaraj@gscloudsolutions.com.enterprise'
  QA_ORG_PASSWORD: ${{ secrets.QA_ORG_PASSWORD }}
  QA_ORG_TYPE: 'PRODUCTION'
  PROD_ORG_TYPE: 'PRODUCTION'
  TEST_LEVEL: 'RunSpecifiedTests'
  CI_CD_PROVIDER: 'AzureDevOps'
  LOGGING_LEVEL: 'debug'
  MANIFEST_VERSION: 52.0

on:
  push:
    branches: [ master ]
    
jobs:
  create_deployment_archive:
    runs-on: ubuntu-latest
    container:
      image: gscloudsolutions/devops-mate-test:github
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Creating Deployment Package for QA Org Valdation
        run: sfPackages source-combined -p $GITHUB_WORKSPACE/$QA_PACKAGE_DIR -n HEAD -i $GITHUB_RUN_NUMBER || if test $? -eq 21; then exit 0; else exit 1; fi

      - name: Archive Deployment Package
        uses: actions/upload-artifact@v2
        with:
          name: fair_ci_cd_artifact
          path: ${{ github.workspace }}/${{ env.QA_PACKAGE_DIR }}/*
          retention-days: 14
 
  deploy_qa:
    name: 'PR-Deploy QA Sandbox'
    runs-on: ubuntu-latest
    container:
      image: gscloudsolutions/devops-mate-test:github
    needs: [ create_deployment_archive ]

    environment: 'QA'
    steps:
      - name: Downloading artifact
        uses: actions/download-artifact@v2
        with:
          name: fair_ci_cd_artifact
          path: ${{ github.workspace }}/${{ env.QA_PACKAGE_DIR }}/

      - name: Deploy QA Sandbox
        run: sfDeploy mdapipackage -u $QA_ORG_USERNAME -s $QA_ORG_PASSWORD -t $QA_ORG_TYPE --notificationTitle 'QA Sandbox Deployment' -p $GITHUB_WORKSPACE/$QA_PACKAGE_DIR --successSHA $GITHUB_SHA -i $GITHUB_RUN_NUMBER -k "SampleTest" -l ${TEST_LEVEL}
